<?xml version="1.0"?>
<robot name="cleaning_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!--Inclusions-->
    <!--Colors-->
    <material name="Gray">
        <color rgba="0.6 1 0.8 1"/>
    </material>

    <material name="DarkGray">
        <color rgba="0.3 0.3 0.3 1"/>
    </material>

    <material name="Orange">
        <color rgba="1 0.6 0 1"/>
    </material>

    <material name="Purple">
        <color rgba="1 0 1 1"/>
    </material>

    <material name="DarkOrange">
        <color rgba="0.7 0.42 0 1"/>
    </material>

    <material name="Green">
        <color rgba="0 1 0 1"/>
    </material>

    <material name="Red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="Blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>

    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>

    <!--Constants-->
    <xacro:property name="M_PI" value="3.141592653589793238462643"/>
    <xacro:property name="M_PI_2" value="1.57079632679" />
    <xacro:property name="DEG_TO_RAD" value="0.01745" />

    <xacro:property name="base_x_to_wheel" value="0.06"/>
    <xacro:property name="base_y_to_wheel" value="0.156"/>
    <xacro:property name="base_z_to_wheel" value="0.05"/>
    <xacro:property name="wheel_separation" value="0.312"/>

    <!--Component dimensions-->
    <xacro:property name="base_h" value="0.11"/>
    <xacro:property name="base_r" value="0.25"/>
    <xacro:property name="base_m" value="10.0" />

    <xacro:property name="caster_h" value="0.02"/>
    <xacro:property name="caster_r" value="0.025"/>
    <xacro:property name="caster_m" value="0.15"/>

    <xacro:property name="caster_rot_h" value="0.06"/>
    <xacro:property name="caster_rot_r" value="0.015"/>
    <xacro:property name="caster_rot_m" value="0.15"/>

    <xacro:property name="br_lft_h" value="0.10"/>
    <xacro:property name="br_lft_r" value="0.0075"/>
    <xacro:property name="br_lft_m" value="0.15"/>

    <xacro:property name="br_con1_h" value="0.09"/>
    <xacro:property name="br_con1_r" value="0.0075"/>
    <xacro:property name="br_con1_m" value="0.15"/>

    <xacro:property name="br_con2_h" value="0.025"/>
    <xacro:property name="br_con2_r" value="0.0075"/>
    <xacro:property name="br_con2_m" value="0.15"/>

    <xacro:property name="br_h" value="0.01"/>
    <xacro:property name="br_r" value="0.065"/>
    <xacro:property name="br_m" value="0.15"/>

    <xacro:property name="whl_h" value="0.03"/>
    <xacro:property name="whl_r" value="0.065"/>
    <xacro:property name="whl_m" value="0.6"/>

    <xacro:property name="hokuyo_size" value="0.05" />

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertia ixx="${10*m*(3*r*r+h*h)/12}" ixy = "0.0" ixz = "0.0" iyy="${10*m*(3*r*r+h*h)/12}" iyz = "0.0" izz="${10*m*r*r/2}"/>
    </xacro:macro>

    <xacro:macro name="wheel" params="fb lr parent translateX translateY flipY"> 
        <link name="${fb}_${lr}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="${flipY*M_PI_2} 0 0" /> 
                <geometry>
                    <cylinder length="${whl_h}" radius="${whl_r}" />
                </geometry>
                <material name="DarkGray" />
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="${flipY*M_PI_2} 0 0" />
                <geometry>
                    <cylinder length="${whl_h}" radius="${whl_r}" />
                </geometry>
            </collision>
            <inertial>
                <mass value="${whl_m}" />
                <origin xyz="0 0 0" />
                <xacro:cylinder_inertia  m="${whl_m}" r="${whl_r}" h="${whl_h}" />
            </inertial>
        </link>

        <gazebo reference="${fb}_${lr}_wheel">
            <mu1 value="1.0"/>
            <mu2 value="1.0"/>
            <kp  value="10000000.0" />
            <kd  value="1.0" />
            <fdir1 value="1 0 0"/>
            <material>Gazebo/Grey</material>
            <turnGravityOff>false</turnGravityOff>
        </gazebo>

        <joint name="${fb}_${lr}_wheel_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="${fb}_${lr}_wheel"/>
            <origin xyz="${translateX * base_x_to_wheel} ${translateY * base_y_to_wheel} ${-base_z_to_wheel}" rpy="0 0 0" /> 
            <axis xyz="0 1 0" rpy="0 0 0" />
            <limit effort="100" velocity="100"/>
            <joint_properties damping="30.0" friction="1.0"/>
        </joint>

    <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${fb}_${lr}_wheel_joint_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${fb}_${lr}_wheel_joint" />
            <actuator name="${fb}_${lr}_wheel_joint_motor">
                <hardwareInterface>EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
   
    </xacro:macro>

    <link name="base_footprint">
        <inertial>
            <mass value="0.0000001"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia    ixx="0.0" ixy="0.0" ixz="0.0"
                        iyy="0.0" iyz="0.0"
                        izz="0.0"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <link name="base_link">
        <inertial>
            <mass value="${base_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia m="${base_m}" r="${base_r}" h="${base_h}"/>
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_h}" radius="${base_r}"/>
            </geometry>
            <material name="White"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${base_h}" radius="${base_r}"/>
            </geometry>
        </collision>
    </link>
 
    <link name="caster_rotator">
        <inertial>
            <mass value="${caster_rot_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${caster_rot_m}" r="${caster_rot_r}" h="${caster_rot_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${caster_rot_h}" radius="${caster_rot_r}"/>
            </geometry>
            <material name="Purple"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${caster_rot_h}" radius="${caster_rot_r}"/>
            </geometry>
        </collision>
    </link>


    <link name="caster">
        <inertial>
            <mass value="${caster_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${caster_m}" r="${caster_r}" h="${caster_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${caster_h}" radius="${caster_r}"/>
            </geometry>
            <material name="DarkOrange"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${caster_h}" radius="${caster_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="brush_lift">
        <inertial>
            <mass value="${br_lft_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_lft_m}" r="${br_lft_h}" h="${br_lft_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_lft_h}" radius="${br_lft_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_lft_h}" radius="${br_lft_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="left_brush_connector1">
        <inertial>
            <mass value="${br_con1_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_con1_m}" r="${br_con1_r}" h="${br_con1_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con1_h}" radius="${br_con1_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con1_h}" radius="${br_con1_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="left_brush_connector2">
        <inertial>
            <mass value="${br_con2_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_con2_m}" r="${br_con2_r}" h="${br_con2_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con2_h}" radius="${br_con2_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con2_h}" radius="${br_con2_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="right_brush_connector1">
        <inertial>
            <mass value="${br_con1_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_con1_m}" r="${br_con1_r}" h="${br_con1_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con1_h}" radius="${br_con1_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con1_h}" radius="${br_con1_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="right_brush_connector2">
        <inertial>
            <mass value="${br_con2_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_con2_m}" r="${br_con2_r}" h="${br_con2_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con2_h}" radius="${br_con2_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_con2_h}" radius="${br_con2_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="left_brush">
        <inertial>
            <mass value="${br_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_m}" r="${br_r}" h="${br_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_h}" radius="${br_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_h}" radius="${br_r}"/>
            </geometry>
        </collision>
    </link>

    <link name="right_brush">
        <inertial>
            <mass value="${br_m}"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <xacro:cylinder_inertia  m="${br_m}" r="${br_r}" h="${br_h}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_h}" radius="${br_r}"/>
            </geometry>
            <material name="Green"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder length="${br_h}" radius="${br_r}"/>
            </geometry>
        </collision>
    </link>  

    <link name="hokuyo_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${hokuyo_size} ${hokuyo_size} ${hokuyo_size}"/>
            </geometry>
            <material name="Blue" />
        </visual>
    </link>

     <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0.12" rpy="0 0 0"/>
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>    

    <joint name="caster_rotator_joint" type="fixed">
        <origin rpy="0 0 0" xyz="-0.15 0 ${-0.06}"/>
        <parent link="base_link"/>
        <child link="caster_rotator"/>
<!--         <axis xyz="0 0 1"/>
       <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>  -->
    </joint>

    <joint name="caster_joint" type="continuous">
        <origin rpy="${M_PI_2} 0 0" xyz="-0.02 0 -0.03"/>
        <parent link="caster_rotator"/>
        <child link="caster"/>
        <axis xyz="0 0 1"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="brush_lift_joint" type="prismatic">
        <origin rpy="0 0 ${M_PI_2}" xyz="0.2 0 ${-base_h/2}"/>
        <parent link="base_link"/>
        <child link="brush_lift"/>
        <axis xyz="0 0 1"/>
        <limit effort="30" velocity="1.0" lower="0" upper="0.035"/>
        <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="left_brush_connector1_joint" type="fixed">
        <origin rpy="0 ${M_PI_2} 0" xyz="0.04 0 -0.04"/>
        <parent link="brush_lift"/>
        <child link="left_brush_connector1"/>
    </joint>

    <joint name="right_brush_connector1_joint" type="fixed">
        <origin rpy="0 ${M_PI_2} 0" xyz="-0.04 0 -0.04"/>
        <parent link="brush_lift"/>
        <child link="right_brush_connector1"/>
    </joint>

    <joint name="left_brush_connector2_joint" type="fixed">
        <origin rpy="0 ${-M_PI_2} 0" xyz="0 0.008 0.04"/>
        <parent link="left_brush_connector1"/>
        <child link="left_brush_connector2"/>
    </joint>

    <joint name="right_brush_connector2_joint" type="fixed">
        <origin rpy="0 ${-M_PI_2} 0" xyz="0 0.008 -0.04"/>
        <parent link="right_brush_connector1"/>
        <child link="right_brush_connector2"/>
    </joint>

    <joint name="left_brush_joint" type="continuous">
        <origin rpy="0 0 0" xyz="0 0 -0.01"/>
        <parent link="left_brush_connector2"/>
        <child link="left_brush"/>
        <axis xyz="0 0 1"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="right_brush_joint" type="continuous">
        <origin rpy="0 0 0" xyz="0 0 -0.01"/>
        <parent link="right_brush_connector2"/>
        <child link="right_brush"/>
        <axis xyz="0 0 1"/>
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>

    <joint name="hokuyo_joint" type="fixed">
        <origin xyz="${base_r - hokuyo_size/2} 0 ${base_h/2+hokuyo_size/2}" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="hokuyo_link" />
    </joint>

    <xacro:wheel fb="front" lr="right" parent="base_link" translateX="1" translateY="-1" flipY="1"/>
    <xacro:wheel fb="front" lr="left" parent="base_link" translateX="1" translateY="1" flipY="1"/>

    
    <gazebo reference="base_footprint">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="base_link">
        <material>Gazebo/White</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="caster_rotator">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>
 
    <gazebo reference="caster">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="brush_lift">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="left_brush_connector1">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="left_brush_connector2">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="right_brush_connector1">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="right_brush_connector2">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="left_brush">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="right_brush">
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <gazebo reference="hokuyo_link">
        <material>Gazebo/Blue</material>
        <turnGravityOff>false</turnGravityOff>
        <sensor type="ray" name="head_hokuyo_sensor">
            <pose>${hokuyo_size/2} 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>40</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>${-M_PI_2}</min_angle>
                        <max_angle>${M_PI_2}</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.10</min>
                    <max>10.0</max>
                    <resolution>0.001</resolution>
                </range>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>hokuyo_link</frameName>
            </plugin>
        </sensor>
    </gazebo>


     <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <legacyMode>true</legacyMode>
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>false</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftJoint>front_left_wheel_joint</leftJoint>
            <rightJoint>front_right_wheel_joint</rightJoint>
            <wheelSeparation>${wheel_separation}</wheelSeparation>
            <wheelDiameter>${2*whl_r}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.5</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryTopic>odom</odometryTopic>
            <robotBaseFrame>base_footprint</robotBaseFrame>
        </plugin>
    </gazebo>

</robot>
